import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AuthContextProvider} from "@/app/context/AuthContext";
import {StrictMode} from "react";
import QueryProvider from "@/app/http/queryClient";
import Header from "@/app/components/Header";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
    <body className={`${inter.className}`}>
    <StrictMode>
      <QueryProvider>
        <AuthContextProvider>
          <span className={"dot-mask"}>
             <div
               className="absolute inset-0 h-full w-full bg-white dark:bg-stone-950 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] dark:bg-[radial-gradient(#0f172a_1px,transparent_1px)] [background-size:16px_16px]">
                <Header/>
               {children}
             </div>
            <Toaster/>
          </span>
        </AuthContextProvider>
      </QueryProvider>
    </StrictMode>
    </body>
    </html>
  );
}
